/* The picture vocabulary for word ↔ picture matching: every emoji the kid tasks use that has ONE clear
   name for a child. Look-alikes are left out on purpose (🐔/🐓, 🧸 next to 🐻, 🍬/🍭, 🌳/🌲, 🐟/🐠…) so a
   sheet never has two right answers. The words themselves live in the i18n strings as `v.<key>`. */
/* `set` groups the pictures like the math picture sets (same names), plus `home` for things around the house */
export const VOCABULARY_SETS = [
  'fruit',
  'veggies',
  'dinos',
  'animals',
  'farm',
  'sea',
  'bugs',
  'sweets',
  'vehicles',
  'space',
  'toys',
  'nature',
  'home',
] as const;
export type VocabularySet = (typeof VOCABULARY_SETS)[number];

export const VOCABULARY: { key: string; pic: string; set: VocabularySet }[] = [
  { key: 'apple', pic: '🍎', set: 'fruit' },
  { key: 'banana', pic: '🍌', set: 'fruit' },
  { key: 'strawberry', pic: '🍓', set: 'fruit' },
  { key: 'orange', pic: '🍊', set: 'fruit' },
  { key: 'pear', pic: '🍐', set: 'fruit' },
  { key: 'grapes', pic: '🍇', set: 'fruit' },
  { key: 'watermelon', pic: '🍉', set: 'fruit' },
  { key: 'cherries', pic: '🍒', set: 'fruit' },
  { key: 'kiwi', pic: '🥝', set: 'fruit' },
  { key: 'pineapple', pic: '🍍', set: 'fruit' },
  { key: 'carrot', pic: '🥕', set: 'veggies' },
  { key: 'corn', pic: '🌽', set: 'veggies' },
  { key: 'broccoli', pic: '🥦', set: 'veggies' },
  { key: 'tomato', pic: '🍅', set: 'veggies' },
  { key: 'potato', pic: '🥔', set: 'veggies' },
  { key: 'onion', pic: '🧅', set: 'veggies' },
  { key: 'pepper', pic: '🌶️', set: 'veggies' },
  { key: 'cucumber', pic: '🥒', set: 'veggies' },
  { key: 'mushroom', pic: '🍄', set: 'veggies' },
  { key: 'dinosaur', pic: '🦕', set: 'dinos' },
  { key: 'dragon', pic: '🐉', set: 'dinos' },
  { key: 'egg', pic: '🥚', set: 'dinos' },
  { key: 'bone', pic: '🦴', set: 'dinos' },
  { key: 'volcano', pic: '🌋', set: 'dinos' },
  { key: 'crocodile', pic: '🐊', set: 'dinos' },
  { key: 'lizard', pic: '🦎', set: 'dinos' },
  { key: 'dog', pic: '🐶', set: 'animals' },
  { key: 'cat', pic: '🐱', set: 'animals' },
  { key: 'rabbit', pic: '🐰', set: 'animals' },
  { key: 'bear', pic: '🐻', set: 'animals' },
  { key: 'fox', pic: '🦊', set: 'animals' },
  { key: 'panda', pic: '🐼', set: 'animals' },
  { key: 'lion', pic: '🦁', set: 'animals' },
  { key: 'pig', pic: '🐷', set: 'animals' },
  { key: 'monkey', pic: '🐵', set: 'animals' },
  { key: 'koala', pic: '🐨', set: 'animals' },
  { key: 'cow', pic: '🐄', set: 'farm' },
  { key: 'sheep', pic: '🐑', set: 'farm' },
  { key: 'hen', pic: '🐔', set: 'farm' },
  { key: 'horse', pic: '🐴', set: 'farm' },
  { key: 'duck', pic: '🦆', set: 'farm' },
  { key: 'goat', pic: '🐐', set: 'farm' },
  { key: 'fish', pic: '🐟', set: 'sea' },
  { key: 'octopus', pic: '🐙', set: 'sea' },
  { key: 'crab', pic: '🦀', set: 'sea' },
  { key: 'turtle', pic: '🐢', set: 'sea' },
  { key: 'dolphin', pic: '🐬', set: 'sea' },
  { key: 'shark', pic: '🦈', set: 'sea' },
  { key: 'whale', pic: '🐳', set: 'sea' },
  { key: 'shell', pic: '🐚', set: 'sea' },
  { key: 'bee', pic: '🐝', set: 'bugs' },
  { key: 'ladybug', pic: '🐞', set: 'bugs' },
  { key: 'butterfly', pic: '🦋', set: 'bugs' },
  { key: 'caterpillar', pic: '🐛', set: 'bugs' },
  { key: 'ant', pic: '🐜', set: 'bugs' },
  { key: 'spider', pic: '🕷️', set: 'bugs' },
  { key: 'snail', pic: '🐌', set: 'bugs' },
  { key: 'lollipop', pic: '🍭', set: 'sweets' },
  { key: 'cupcake', pic: '🧁', set: 'sweets' },
  { key: 'cookie', pic: '🍪', set: 'sweets' },
  { key: 'donut', pic: '🍩', set: 'sweets' },
  { key: 'cake', pic: '🎂', set: 'sweets' },
  { key: 'chocolate', pic: '🍫', set: 'sweets' },
  { key: 'icecream', pic: '🍦', set: 'sweets' },
  { key: 'car', pic: '🚗', set: 'vehicles' },
  { key: 'bus', pic: '🚌', set: 'vehicles' },
  { key: 'train', pic: '🚂', set: 'vehicles' },
  { key: 'plane', pic: '✈️', set: 'vehicles' },
  { key: 'rocket', pic: '🚀', set: 'vehicles' },
  { key: 'bicycle', pic: '🚲', set: 'vehicles' },
  { key: 'tractor', pic: '🚜', set: 'vehicles' },
  { key: 'boat', pic: '⛵', set: 'vehicles' },
  { key: 'helicopter', pic: '🚁', set: 'vehicles' },
  { key: 'scooter', pic: '🛴', set: 'vehicles' },
  { key: 'star', pic: '⭐', set: 'space' },
  { key: 'moon', pic: '🌙', set: 'space' },
  { key: 'sun', pic: '☀️', set: 'space' },
  { key: 'planet', pic: '🪐', set: 'space' },
  { key: 'rainbow', pic: '🌈', set: 'space' },
  { key: 'cloud', pic: '☁️', set: 'space' },
  { key: 'snowflake', pic: '❄️', set: 'space' },
  { key: 'lightning', pic: '⚡', set: 'space' },
  { key: 'comet', pic: '☄️', set: 'space' },
  { key: 'ufo', pic: '🛸', set: 'space' },
  { key: 'robot', pic: '🤖', set: 'toys' },
  { key: 'balloon', pic: '🎈', set: 'toys' },
  { key: 'ball', pic: '⚽', set: 'toys' },
  { key: 'gift', pic: '🎁', set: 'toys' },
  { key: 'puzzle', pic: '🧩', set: 'toys' },
  { key: 'tree', pic: '🌳', set: 'nature' },
  { key: 'sunflower', pic: '🌻', set: 'nature' },
  { key: 'tulip', pic: '🌷', set: 'nature' },
  { key: 'leaf', pic: '🍁', set: 'nature' },
  { key: 'cactus', pic: '🌵', set: 'nature' },
  { key: 'clover', pic: '🍀', set: 'nature' },
  { key: 'palm', pic: '🌴', set: 'nature' },
  { key: 'rock', pic: '🪨', set: 'nature' },
  { key: 'house', pic: '🏠', set: 'home' },
  { key: 'island', pic: '🏝️', set: 'home' },
  { key: 'cheese', pic: '🧀', set: 'home' },
  { key: 'bath', pic: '🛁', set: 'home' },
  { key: 'web', pic: '🕸️', set: 'home' },
  { key: 'mousetrap', pic: '🪤', set: 'home' },
  { key: 'broom', pic: '🧹', set: 'home' },
  { key: 'trafficlight', pic: '🚦', set: 'home' },
  { key: 'mouse', pic: '🐭', set: 'home' },
];
